Actually fail the linting check if there are suggestions

diff --git a/.github/workflows/cpp-linter.yaml b/.github/workflows/cpp-linter.yaml
--- a/.github/workflows/cpp-linter.yaml
+++ b/.github/workflows/cpp-linter.yaml
@@ -51,7 +51,7 @@ jobs:
 
       - name: Fail fast?!
         if: steps.linter.outputs.checks-failed != 0
-        run: |
-          echo "some linter checks failed. ${{ steps.linter.outputs.checks-failed }}"
+        #run: |
+        #  echo "some linter checks failed. ${{ steps.linter.outputs.checks-failed }}"
         # for actual deployment
-        # run: exit 1
+        run: exit 1
